name: Run Unity Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    name: Run EditMode Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Unity Tests
      uses: game-ci/unity-test-runner@v4
      with:
        unityVersion: 2023.2.0f1
        testMode: editmode
        projectPath: .
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
